#!/bin/bash

# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source_dir="${1:?App source directory is required first arg}"
output_dir="${2:?Build output directory is required second arg}"

echo 1 > "$output_dir/exitcode"

exec > >(tee "$output_dir/output_log.txt")
exec 2>&1

log:date-time() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

main() {
  log:date-time > "$output_dir/starttime"
  [[ -e deploy_output/applicationurl ]] && APPLICATION_URL=$(cat deploy_output/applicationurl) || APPLICATION_URL='' 
  (
    set -ex
    task
  )
  cp -pr "$source_dir" "$output_dir/app"
  log:date-time > "$output_dir/endtime"
  echo 0  > "$output_dir/exitcode"
}

die() { echo "$@" 1>&2 ; exit 1; }

task() {
  die "Please define the function: 'task'"
}
